"""empty message

Revision ID: 1830a394e372
Revises:
Create Date: 2019-04-16 20:29:04.733198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1830a394e372' # pylint: disable=invalid-name
down_revision = None # pylint: disable=invalid-name
branch_labels = None # pylint: disable=invalid-name
depends_on = None # pylint: disable=invalid-name


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_user')  # pylint: disable=no-member
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',  # pylint: disable=no-member
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('date_created', sa.DATETIME(), nullable=True),
                    sa.Column('date_modified', sa.DATETIME(), nullable=True),
                    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
                    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
                    sa.Column('password_hash', sa.VARCHAR(
                        length=192), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###
