"""empty message

Revision ID: a6f74d98fb0f
Revises: 
Create Date: 2018-06-21 22:49:26.779752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f74d98fb0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('deleted', sa.String(length=128), server_default='no', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'deleted')
    # ### end Alembic commands ###
